language: node_js
node_js: 6.11.0

cache: true

install:
  - npm i

script:
  - npm run test

cache:
  enabled: true
  directories:
  - ./node_modules
  
before_install:
  - git config --global user.email "deploy@vexor.io"
  - git config --global user.name "Vexor CI"
  - git config --global url.ssh://git@github.com/.insteadOf https://github.com/

deploy:
  - branch: "development"
    shell:
      - "DEPLOY_TO=develop OVERRIDE_VALUES=values.develop.yaml ZONE=europe-west1-b ./deploy/scripts/deploy.sh"

  - branch: "production"
    shell:
      - "DEPLOY_TO=humaniq-production OVERRIDE_VALUES=values.yaml ZONE=europe-west1-b ./deploy/scripts/deploy.sh"
  