language: node_js
node_js: 6.11.0

install:
  - npm i

script:
  - npm run test

cache:
  enabled: true
  directories:
  - ./node_modules

deploy:
  - branch: "master"
    shell:
      - "DEPLOY_TO=humaniq-static ./scripts/deploy.sh"
